### ISSUE TITLE
Implement book search

### ISSUE THREAD

**Issue by iTKerry** [better-open-source/better-read-shared#2]
## Description

There is a [website](http://loveread.me/) where you can read books for free. For now we have some logic which can parse them. So, now we need also some search service, which will allow us to get book url or book identifier. You need to find the way of how to create search request and handle the response.

## Technical Notes

* Write your services / repositories in [TAP](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap)
* Output object should contain next info: book identifier, book name, author name, book url (contains book identifier)

**!UPDATE!**

Please, use **_loveread.me_ for search** and **_loveread.ec_ for scraping books**.
**_loveread.me_ for search** provides book image while search, also it supports next search filters:

1. book name
2. author
3. books series

We need to handle all of these 3 cases. Also we need to implement scraping of book series and author biography (included all books and series related to him)

## Acceptable Criteria

- [ ] Output result should be list of books info

**Comment by iTKerry** [comment]
@idk-ctrl any progress with this?

**Comment by iTKerry** [comment]
@idk-ctrl are you still working on it?

**Comment by lvyyln** [comment]
@iTKerry start working on it
